//! PANDA JSON File Formats
//!
//! Schemas for the JSON configuration files used by the PANDA prover and verifier.
//! These structs are used by the standalone command-line tools to deserialize user inputs.

use serde::Deserialize;

/// The main benchmark fixture defining the DNN, the input bounds, and the property.
/// 
/// This JSON file (often generated by Python) contains all the mathematical 
/// parameters of the neural network and the exact robustness property 
/// that the zero-knowledge proof will certify.
#[derive(Debug, Deserialize, Clone)]
pub struct Fixture {
    /// Optional name of the fixture.
    #[serde(default)]
    pub name: Option<String>,
    /// Optional description of what this fixture tests.
    #[serde(default)]
    pub description: Option<String>,
    /// Optional description of the network architecture (e.g., "3x256").
    #[serde(default)]
    pub architecture: Option<String>,
    /// Optional description of the property being proved.
    #[serde(default)]
    pub property_description: Option<String>,
    /// Optional declared input dimension. If omitted, it is inferred from x_lower.
    #[serde(default)]
    pub input_dim: Option<usize>,
    /// Optional declared output dimension. If omitted, it is inferred from the last layer's weights.
    #[serde(default)]
    pub output_dim: Option<usize>,

    /// A list of activation functions for each layer (e.g., "relu", "sigmoid", "tanh").
    pub activations: Vec<String>,
    /// The linear weights of the neural network, shape `[layers][out_features][in_features]`.
    pub weights: Vec<Vec<Vec<f64>>>,
    /// The biases for each linear layer, shape `[layers][out_features]`.
    pub biases: Vec<Vec<f64>>,
    /// The lower bounds of the allowed input perturbation region.
    pub x_lower: Vec<f64>,
    /// The upper bounds of the allowed input perturbation region.
    pub x_upper: Vec<f64>,
    /// The linear property matrix C that we are proving a bound for.
    pub spec_c: Vec<Vec<f64>>,
    /// The linear property bias vector d that we are proving a bound for.
    pub spec_d: Vec<f64>,
    /// The side of the bound to prove. Usually "lower" or "upper".
    pub side: String,
    /// The requested bit precision for the fixed-point quantization engine.
    pub precision_bits: i32,
}

/// The cryptographic quantization parameters for the SNARK.
///
/// This JSON file configures the exact budgets and scales used by the zero-knowledge
/// proof. Both the prover and verifier must agree on these parameters.
#[derive(Debug, Deserialize, Clone)]
pub struct QuantParams {
    /// Overloaded from the fixture to ensure parameter consistency across the pipeline.
    pub precision_bits: Option<i32>,
    /// The signed range-table half-width (e.g., 14 for a 14-bit lookup table).
    pub table_bits: i32,
    /// The budget for the final-pass output-margin range checks.
    pub out_bound_range_bits: usize,
    /// The budget for every per-neuron gadget range check. If omitted, defaults to out_bound_range_bits.
    pub gadget_range_bits: Option<usize>,
    /// Overrides for the sigmoid scaling factor. If omitted, it is automatically derived from precision_bits.
    pub sigma_x_scale_log2: Option<i32>,
    /// Overrides for the tanh scaling factor. If omitted, it is automatically derived from precision_bits.
    pub sigma_v_scale_log2: Option<i32>,
    /// Scale factor for the input box quantization. If omitted, the engine uses an auto-scaling heuristic.
    pub input_scale_log2: Option<i32>,
}
